name: nuget push
description: add nuget sources before restore
inputs:
  nuser:
    required: true
    type: string
  npass:
    required: true
    type: string
  NUGET_KEY:
    required: true
    type: string  
runs:
  using: "composite"
  steps:
  - name: NugetSetup
    run: |
      dotnet nuget add source ${{ inputs.NUGET_SOURCE }} -n temp  --store-password-in-clear-text --username ${{ inputs.nuser }} --password ${{ inputs.npass }}
      dotnet restore    
    shell: bash
